# Generated by Django 5.0.6 on 2025-03-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_testdrivebooking_options_alter_car_make_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold')], default='AVAILABLE', max_length=20),
        ),
    ]
