# Generated by Django 5.0.6 on 2025-03-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_car_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsubmission',
            name='kilometers_driven',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='carsubmission',
            name='transmission_type',
            field=models.CharField(default='Manual', max_length=20),
        ),
    ]
