# Generated by Django 5.0.6 on 2026-05-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_carsubmission_kilometers_driven_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG'), ('ELECTRIC', 'Electric')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='insurance_type',
            field=models.CharField(choices=[('Comprehensive', 'Comprehensive'), ('Third-Party', 'Third-Party'), ('No Insurance', 'No Insurance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='insurance_validity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(choices=[('Maruti', 'Maruti'), ('Hyundai', 'Hyundai'), ('Tata', 'Tata'), ('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Ford', 'Ford'), ('Kia', 'Kia'), ('Renault', 'Renault'), ('Skoda', 'Skoda'), ('Mahindra', 'Mahindra'), ('Nissan', 'Nissan'), ('Volkswagen', 'Volkswagen'), ('MG', 'MG'), ('Jeep', 'Jeep')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='registration_month',
            field=models.CharField(choices=[('Jan', 'january'), ('Feb', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], default='jan', max_length=20),
        ),
    ]
